# Generated by Django 5.0 on 2024-01-12 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='plant_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Name', max_length=50, unique=True)),
                ('mob_num', models.CharField(max_length=13, unique=True)),
                ('photo', models.ImageField(upload_to='photos')),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=20, unique=True)),
                ('password2', models.CharField(max_length=20, unique=True)),
                ('nursery_address', models.TextField()),
                ('approve', models.BooleanField(default=False)),
            ],
        ),
    ]
