# Generated by Django 5.0 on 2024-01-12 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant_admin',
            name='password2',
        ),
    ]
