# Generated by Django 5.0 on 2024-01-16 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_plant_admin_password1'),
        ('cart', '0003_checkout_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='plant_admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.plant_admin'),
        ),
    ]
