# Generated by Django 5.0 on 2024-02-07 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_checkout_plant_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='plant_admin',
        ),
    ]
