# Generated by Django 5.0 on 2024-02-14 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_checkout_plant_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('customer_checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.checkout')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.items')),
            ],
        ),
    ]
