# Generated by Django 5.0 on 2023-12-30 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_plants',
            name='img',
            field=models.ImageField(upload_to='picture'),
        ),
    ]
