# Generated by Django 5.0 on 2024-01-03 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_add_plants_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_plants',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
