# Generated by Django 5.0 on 2024-01-12 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('home', '0003_add_plants_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_plants',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.plant_admin'),
        ),
    ]
